basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Swagger Example API
  version: "1.0"
paths:
  /ping:
    get:
      description: API để kiểm tra kết nối server
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: Ping Example
      tags:
      - example
swagger: "2.0"
